// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yscpcikasejxqjyadszh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzY3BjaWthc2VqeHFqeWFkc3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTQ1NzIsImV4cCI6MjA2MjEzMDU3Mn0.2G_IOPjAxTF3OrO1sHGYm-HyFCMX0CU__3nn8-ar7cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);